# Generated by Django 3.2.7 on 2021-09-25 08:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Likelion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likelion_first', models.CharField(max_length=200, verbose_name='멋 likelion_first')),
                ('likelion_second', models.CharField(max_length=200, verbose_name='사 likelion_first')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='최근 순 created')),
                ('like_users', models.ManyToManyField(related_name='like_counts', to=settings.AUTH_USER_MODEL, verbose_name='좋아요 수 like_users')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자 writer')),
            ],
        ),
        migrations.CreateModel(
            name='Growl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('growl_first', models.CharField(max_length=200, verbose_name='어 growl_first')),
                ('growl_second', models.CharField(max_length=200, verbose_name='흥 growl_first')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='최근 순 created')),
                ('like_users', models.ManyToManyField(related_name='growl_like_counts', to=settings.AUTH_USER_MODEL, verbose_name='좋아요 수 like_users')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자 writer')),
            ],
        ),
    ]
