# Generated by Django 3.2.7 on 2021-09-25 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='growl',
            name='like_counts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='likelion',
            name='like_counts',
            field=models.IntegerField(default=0),
        ),
    ]
