# Generated by Django 3.2.7 on 2021-09-25 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210925_0558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='growl',
            name='like_counts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='likelion',
            name='like_counts',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
