# Generated by Django 3.2.7 on 2021-09-25 08:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_alter_likelion_like_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likelion',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='최근 순 created'),
        ),
        migrations.AlterField(
            model_name='likelion',
            name='likelion_first',
            field=models.CharField(max_length=200, null=True, verbose_name='멋 likelion_first'),
        ),
        migrations.AlterField(
            model_name='likelion',
            name='likelion_second',
            field=models.CharField(max_length=200, null=True, verbose_name='사 likelion_first'),
        ),
        migrations.AlterField(
            model_name='likelion',
            name='writer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자 writer'),
        ),
    ]
